---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.0"
    name: elastic
  - src: git@github.com:Dmitriy-Guskov/kibana-role.git
    scm: git
    version: "2.0.1"
    name: kibana
  - src: git@github.com:Dmitriy-Guskov/filebeat-role.git
    scm: git
    version: "2.0.0"
    name: filebeat